import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const personaPath = join(root, 'peeyush_persona.md');
const outputPath = join(root, 'api', 'lib', 'personaContent.ts');

const persona = readFileSync(personaPath, 'utf-8');

writeFileSync(
  outputPath,
  `// Auto-generated by scripts/embed-persona.mjs — do not edit manually\nexport const PERSONA_DOCUMENT = ${JSON.stringify(persona)};\n`,
  'utf-8',
);

console.log('Embedded peeyush_persona.md into api/lib/personaContent.ts');
